### ISSUE TITLE
Server Restart

### ISSUE THREAD

**Issue by Romulus10** [InsidiousMind/Gomoku#31]
The server has to be restarted between every game or player 1 segfaults.

**Comment by InsidiousMind** [comment]
This will be fixed when the server implementation for multiple games is done.

Basically the server can't have more than two clients at once. So if two players play a game, the game ends, and the player tries to play another game, on the server the client count would be "3" and it would go to a condition sending a string literal along the lines of something like "Sorry but there are two players already", whilst the client is expecting a gips structure.

This mix up of data causes a segfault

**Comment by InsidiousMind** [comment]
This works now

Not that the mutliple games works, but the server does not require a restart in order to play another game after the current one is finished.
