### ISSUE TITLE
Stones are not put in the expected locations in some cases.

### ISSUE THREAD

**Issue by Romulus10** [InsidiousMind/Gomoku#33]

**Comment by InsidiousMind** [comment]
Give an example so I can reproduce server side, should be an easy fix

**Comment by Romulus10** [comment]
I think the problem here is that we're indexing from 0. Bi said we were having a problem, I don't know.

**Comment by Romulus10** [comment]
I KNOW WHAT HAPPENED
Okay so issue #43 talks about this. It just LOOKS wrong because each turn is offset by a couple displays. I think we're updating the board wrong in the server. I don't know how yet though.

**Comment by InsidiousMind** [comment]
I think you're right, in an earlier version of the game the board would not update correctly and it was delayed

In any case, I fixed #43 , that was caused because of somethin i did last night, but it's OK now, and I think it works in general now
