### ISSUE TITLE
Win checks don't always return proper winning conditions.

### ISSUE THREAD

**Issue by Romulus10** [InsidiousMind/Gomoku#34]

**Comment by InsidiousMind** [comment]
I think i fixed this, i'm not totally certain, and it probably requires some more testing, but from what I tested tonight it works

**Comment by InsidiousMind** [comment]
The client should check for invalid moves, since it has all the information it needs in order to do so. It would be wasteful and clutter up the code on the server to send packets back and forth with that information

**Comment by InsidiousMind** [comment]
I think this has been solved
