### ISSUE TITLE
Decide on code standards 

### ISSUE THREAD

**Issue by InsidiousMind** [InsidiousMind/Gomoku#41]
Ok, so, every programmer has their own style. But for the purposes of this project we should decide on one in order to maintain some kind of fluency throughout. 

I feel like we have some of it down :
2space indents 
Brackets don't have their own lines 

Things we should figure out: 
I feel like we should use camelCase but we have both been like, alternative between doing_something_like_this and camelCase 
We should probably make that all camelCase as per most standards 

Can't think of anything else that's different, but there probs is 

PS - il fix where I made the brackets with their own lines :P

**Comment by Romulus10** [comment]
Yeah, when I write C I tend to format_my_names_like_this because that's kind of more accepted for the language but camelCase is probably more correct. We'll take care of that.

**Comment by InsidiousMind** [comment]
Nah I do the same thing, it's a bad habit

It's going to be easier to read commit history if we decide on standards, though, that way it's easier to zero-in on changes that possibly made things go wrong

**Comment by Romulus10** [comment]
I keep forgetting and naming all of my variables_like_this.

**Comment by InsidiousMind** [comment]
same,

It's difficult because some of the C libs and Bi's code has stuff_like_this

but then i'm like, camelCase or_like_this

I'm so conflicted right now

**Comment by InsidiousMind** [comment]
screw standards

we should be good
