### ISSUE TITLE
Database - query based on username

### ISSUE THREAD

**Issue by Romulus10** [InsidiousMind/Gomoku#45]

**Comment by InsidiousMind** [comment]
I'm thinking the database is going to be serverside, for some reason I thought it was going to be clientside

then I realized it would be bad to have every client with every other clients player_info in it.

So, I've designed the shared variables between clients in such a way that the format wil make it possible to fit into a linked list.

then before the client closes all that's needed is to record the info in this struct to a file, and if the client wants to query it they can.

**Comment by Romulus10** [comment]
This function is finished.
